### ISSUE TITLE
Bright red on collapse

### ISSUE THREAD

**Issue by atkinsonm** [nhanna95/epic-gamer-theme#2]
When collapsing a section of code (Python, JSON, possibly other languages), the line is highlighted in bright red. It's unpleasant to look at and not fitting with the rest of the theme's colors.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3342243/220965552-97ced682-dbec-4160-9503-0336a1f2dcd7.png">

**Comment by nhanna95** [comment]
You shouldn't be collapsing your code, it can decrease overall comprehension and efficiency, so I wanted the theme to discourage this bad habit.
